services:
  app:
    build: .
    container_name: proviemplea_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: proviemplea_mysql
    restart: always
    environment:
      MYSQL_DATABASE: proviemplea
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3307:3306"